Repository jenkins-infra/docs.jenkins.io, pull requests merged in 2024-10, with the labels that each got.

#119 Fix favicon aspect ratio bug
  ui/src/static/favicon.png
Labels: hacktoberfest-accepted

#134 make about.adoc blueocean root
  docs/projects/modules/blueocean/nav.adoc
Labels: hacktoberfest-accepted

#114 feat: Added remaining supporters SVG's from jenkins homepage
  site/public/images/images/sponsors/aws.svg
  site/public/images/images/sponsors/cdf.svg
  site/public/images/images/sponsors/cloudbees.svg
  site/public/images/images/sponsors/github.svg
  site/public/images/images/sponsors/jfrog.svg
  site/public/images/images/sponsors/osuosl.svg
  site/src/components/Jumbotron.js
  site/src/css/index.module.css
  site/static/images/images/sponsors/aws.svg
  site/static/images/images/sponsors/cdf.svg
  site/static/images/images/sponsors/cloudbees.svg
  site/static/images/images/sponsors/github.svg
  site/static/images/images/sponsors/jfrog.svg
  site/static/images/images/sponsors/osuosl.svg
Labels: hacktoberfest-accepted

#149 Remove auto-generated files built with `gatsby develop` command
  site/public/manifest.webmanifest
  site/public/page-data/404.html/page-data.json
  site/public/page-data/author/AbhyudayaSharma/page-data.json
  site/public/page-data/author/Sagar2366/page-data.json
  site/public/page-data/blog/2023/09/21/2023-09-21-jenkins-august-newsletter/page-data.json
  site/public/page-data/blog/2023/09/24/2023-09-24-building-jenkinsio-with-alternative-tools/page-data.json
  site/public/page-data/blog/2023/10/12/2023-10-12-jenkins-september-newsletter/page-data.json
  site/public/page-data/blog/2023/10/25/2023-10-25-what-is-the-plugin-health-score/page-data.json
  site/public/page-data/blog/2023/11/10/2023-11-10-jenkins-october-newsletter/page-data.json
  site/public/page-data/blog/2023/11/2023-11-06-introducing-2-2-2-java-support-plan/page-data.json
  site/public/page-data/blog/page-data.json
  site/public/page-data/changelog-lts/page-data.json
  site/public/page-data/changelog-weekly/page-data.json
  site/public/page-data/dev-404-page/page-data.json
  site/public/page-data/index/page-data.json
  site/public/page-data/sq/d/305747813.json
  site/public/page-data/sq/d/3159585216.json
  site/public/page-data/steps/add-changes-to-build-changelog/page-data.json
  site/public/page-data/steps/git-changelog/page-data.json
  site/public/page-data/steps/parallel-test-executor/page-data.json
  site/public/page-data/steps/parasoft-findings/page-data.json
  site/public/page-data/upgrade-guide/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-107-1/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-107-2/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-107-3/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-138-1/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-235-2/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-235-5/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-249-1/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-263-2/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-277-1/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-277-4/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-32-2/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-426-2/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-426-3/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-440-1/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-440-2/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-46-1/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-46-3/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-60-1/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-60-2/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-7-4/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-73-1/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-73-2/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-73-3/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-89-3/page-data.json
  site/public/page-data/upgrade-guide/upgrades/2-89-4/page-data.json
  site/public/~partytown/debug/partytown-atomics.js
  site/public/~partytown/debug/partytown-media.js
  site/public/~partytown/debug/partytown-sandbox-sw.js
  site/public/~partytown/debug/partytown-sw.js
  site/public/~partytown/debug/partytown-ww-atomics.js
  site/public/~partytown/debug/partytown-ww-sw.js
  site/public/~partytown/debug/partytown.js
  site/public/~partytown/partytown-atomics.js
  site/public/~partytown/partytown-media.js
  site/public/~partytown/partytown-sw.js
  site/public/~partytown/partytown.js
Labels: hacktoberfest-accepted

#148 chore: remove `public/files`
  site/public/files/2015-Jenkins-Community-Survey-Results.pdf
  site/public/files/2016-jenkins-community-survey-responses.pdf
  site/public/files/2016-jenkins-community-survey.pdf
  site/public/files/2016/jenkins-world/freestyle-to-pipelines.pdf
  site/public/files/2016/jenkins-world/jenkins-and-docker.pdf
  site/public/files/2016/jenkins-world/large-git-repos.pdf
  site/public/files/Jenkins-hearts-Ruby.pdf
  site/public/files/State-of-Jenkins-Infographic-2015.pdf
  site/public/files/rate.js
  site/public/files/sf-jam-azure/Scaling Jenkins for CD with Azure.pdf
  site/public/files/sf-jam-azure/Scaling Jenkins with Azure.pdf
Labels: hacktoberfest-accepted

#153 Bugfix/missing svg
  ui/src/css/header.css
  ui/src/img/3-line-menu.svg
  ui/src/partials/head-icons.hbs
Labels: hacktoberfest-accepted

#120 fix: specify width of the Blue Ocean image
  docs/projects/modules/blueocean/pages/about.adoc
Labels: hacktoberfest-accepted

#151 fix: adjusted iframe size for desktop and mobile view for Blue Ocean About page
  docs/projects/modules/blueocean/pages/about.adoc
Labels: hacktoberfest-accepted

#155 updated iframe size on user-docs/2.452.x/blueocean/
  docs/user-docs/modules/blueocean/pages/index.adoc
Labels: hacktoberfest-accepted

#141 feat: add CONTRIBUTING guide
  CONTRIBUTING.adoc
Labels: hacktoberfest-accepted

#135 Update the documentation at "README.adoc"
  README.adoc
Labels: hacktoberfest-accepted

#158 fix: symbol and video size update
  docs/user-docs/modules/blueocean/pages/index.adoc
Labels: bug, hacktoberfest-accepted

#161 Update the documentation at site/ for the Gatsby-based jenkins.io website #123
  README.adoc
  site/README.md
Labels: documentation, hacktoberfest-accepted

#162 fix: Fixed Suggest a presentation UI
  docs/projects/modules/jam/pages/suggest.adoc
Labels: enhancement, hacktoberfest-accepted

#163 implemented update for site/advisories
  site/advisories/2023-07-12.adoc
  site/advisories/2023-07-26.adoc
  site/advisories/2023-08-16.adoc
  site/advisories/2023-09-06.adoc
  site/advisories/2023-09-20.adoc
  site/advisories/2023-10-18.adoc
  site/advisories/2023-10-25.adoc
  site/advisories/2023-11-29.adoc
  site/advisories/2023-12-13.adoc
  site/advisories/2024-01-24.adoc
  site/advisories/2024-03-06.adoc
  site/advisories/2024-03-20.adoc
  site/advisories/2024-04-17.adoc
  site/advisories/2024-05-02.adoc
  site/advisories/2024-05-24.adoc
  site/advisories/2024-06-26.adoc
  site/advisories/2024-08-07.adoc
  site/advisories/2024-10-02.adoc
Labels: hacktoberfest-accepted

#172 feat: added dark mode support to Antora docs
  site/src/css-asciidoc/doc.css
  ui/src/css/base.css
  ui/src/css/doc.css
  ui/src/css/footer.css
  ui/src/css/nav.css
  ui/src/css/toc.css
  ui/src/css/toolbar.css
  ui/src/css/vars.css
Labels: hacktoberfest-accepted
